/* AUTO-GENERATED by scripts/sync-presshouse.mjs — do not edit by hand. */
/* Source: https://shop.playdjgames.com (live PRESS HOUSE catalog). */
import type { StoreProduct } from "./store";

export const PRESS_HOUSE_SYNCED_AT = "2026-09-28T01:10:24.574Z";

export const PRESS_HOUSE_PRODUCTS: StoreProduct[] = [
  {
    "id": "prod_house_mark_tee",
    "name": "House Mark Tee",
    "tagline": "Heavyweight cotton, centered house mark",
    "description": "The house mark, printed small and centered on a heavyweight combed cotton tee. Boxy modern fit with a ribbed collar that holds its shape past the first wash.",
    "details": [
      "4.2 oz combed ring-spun cotton",
      "Boxy modern fit",
      "Water-based print, soft hand"
    ],
    "price": 34,
    "currency": "USD",
    "images": ["https://images-api.printify.com/mockup/6ab92ea0a4fc0c9922093aa5/18542/102044/house-mark-tee.jpg?camera_label=front-2"],
    "category": "Apparel",
    "status": "available",
    "statusLabel": "In stock",
    "options": [
      {
        "id": "size",
        "name": "Size",
        "values": [
          {
            "id": "size-0",
            "label": "S",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-1",
            "label": "M",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-2",
            "label": "L",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-3",
            "label": "XL",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-4",
            "label": "XXL",
            "available": true,
            "priceDelta": 3
          }
        ]
      },
      {
        "id": "color",
        "name": "Color",
        "values": [
          {
            "id": "color-0",
            "label": "Black",
            "available": true
          },
          {
            "id": "color-1",
            "label": "Bone",
            "available": true
          },
          {
            "id": "color-2",
            "label": "Slate",
            "available": true
          }
        ]
      }
    ],
    "url": "https://shop.playdjgames.com/product/house-mark-tee",
    "featured": true
  },
  {
    "id": "prod_wordmark_hoodie",
    "name": "Wordmark Hoodie",
    "tagline": "Brushed fleece with chest wordmark",
    "description": "Midweight brushed-back fleece pullover with the house wordmark across the chest. Double-lined hood, no drawcord aglets, split kangaroo pocket.",
    "details": [
      "8 oz brushed-back fleece",
      "Double-lined hood",
      "Relaxed fit, drop shoulder"
    ],
    "price": 72,
    "currency": "USD",
    "images": ["https://images-api.printify.com/mockup/6ab92ea563d317ccfb0c76d0/32920/98424/wordmark-hoodie.jpg?camera_label=front"],
    "category": "Apparel",
    "status": "available",
    "statusLabel": "In stock",
    "options": [
      {
        "id": "size",
        "name": "Size",
        "values": [
          {
            "id": "size-0",
            "label": "S",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-1",
            "label": "M",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-2",
            "label": "L",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-3",
            "label": "XL",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-4",
            "label": "XXL",
            "available": true,
            "priceDelta": 3
          }
        ]
      },
      {
        "id": "color",
        "name": "Color",
        "values": [
          {
            "id": "color-0",
            "label": "Black",
            "available": true
          },
          {
            "id": "color-1",
            "label": "Slate",
            "available": true
          },
          {
            "id": "color-2",
            "label": "Navy",
            "available": true
          }
        ]
      }
    ],
    "url": "https://shop.playdjgames.com/product/wordmark-hoodie",
    "featured": true
  },
  {
    "id": "prod_grid_long_sleeve",
    "name": "Grid Long Sleeve",
    "tagline": "Sleeve-hit grid pattern, cotton jersey",
    "description": "Long sleeve cotton jersey with the grid motif running down the left sleeve and a small mark at the chest. Cuffs are ribbed and hold tight.",
    "details": [
      "6 oz cotton jersey",
      "Ribbed cuffs",
      "Sleeve and chest placement"
    ],
    "price": 46,
    "currency": "USD",
    "images": ["https://images-api.printify.com/mockup/6ab92ea9dcd154052a0154ef/33798/105264/grid-long-sleeve.jpg?camera_label=front"],
    "category": "Apparel",
    "status": "available",
    "statusLabel": "In stock",
    "options": [
      {
        "id": "size",
        "name": "Size",
        "values": [
          {
            "id": "size-0",
            "label": "S",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-1",
            "label": "M",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-2",
            "label": "L",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-3",
            "label": "XL",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-4",
            "label": "XXL",
            "available": true,
            "priceDelta": 3
          }
        ]
      },
      {
        "id": "color",
        "name": "Color",
        "values": [
          {
            "id": "color-0",
            "label": "Black",
            "available": true
          },
          {
            "id": "color-1",
            "label": "Navy",
            "available": true
          }
        ]
      }
    ],
    "url": "https://shop.playdjgames.com/product/grid-long-sleeve",
    "featured": true
  },
  {
    "id": "prod_house_tote",
    "name": "House Tote",
    "tagline": "Heavy canvas, flat-bottom, long strap",
    "description": "Heavy natural canvas tote with a flat bottom gusset and straps long enough for the shoulder. Printed one side with the house mark.",
    "details": [
      "12 oz cotton canvas",
      "Flat bottom gusset",
      "28 in shoulder straps"
    ],
    "price": 28,
    "currency": "USD",
    "images": ["https://images-api.printify.com/mockup/6ab92eac313d78541609a09c/101409/93895/house-tote.jpg?camera_label=front"],
    "category": "Apparel",
    "status": "available",
    "statusLabel": "In stock",
    "options": [
      {
        "id": "color",
        "name": "Color",
        "values": [
          {
            "id": "color-0",
            "label": "Bone",
            "available": true
          },
          {
            "id": "color-1",
            "label": "Black",
            "available": true
          }
        ]
      }
    ],
    "url": "https://shop.playdjgames.com/product/house-tote",
    "featured": false
  },
  {
    "id": "prod_dad_hat",
    "name": "Dad Hat",
    "tagline": "Unstructured six-panel, curved brim",
    "description": "Unstructured six-panel cap in cotton twill with a low profile and a curved brim. Embroidered mark at the front panel, metal slide closure.",
    "details": [
      "Washed cotton twill",
      "Unstructured low profile",
      "Metal slide closure"
    ],
    "price": 32,
    "currency": "USD",
    "images": ["https://images-api.printify.com/mockup/6ab92eaf63d317ccfb0c76d4/105381/102307/dad-hat.jpg?camera_label=front"],
    "category": "Hats",
    "status": "available",
    "statusLabel": "In stock",
    "options": [
      {
        "id": "color",
        "name": "Color",
        "values": [
          {
            "id": "color-0",
            "label": "Black",
            "available": true
          },
          {
            "id": "color-1",
            "label": "Bone",
            "available": true
          },
          {
            "id": "color-2",
            "label": "Navy",
            "available": true
          }
        ]
      }
    ],
    "url": "https://shop.playdjgames.com/product/dad-hat",
    "featured": true
  },
  {
    "id": "prod_camp_cap",
    "name": "Five-Panel Camp Cap",
    "tagline": "Flat brim, nylon strap, embroidered mark",
    "description": "Five-panel camp cap with a flat brim and the monogram embroidered at the front. Nylon webbing strap with a metal clip at the back.",
    "details": [
      "Cotton twill crown",
      "Flat brim",
      "Nylon webbing strap"
    ],
    "price": 36,
    "currency": "USD",
    "images": ["https://images-api.printify.com/mockup/6ab92eb2a4fc0c9922093aaf/119157/109584/five-panel-camp-cap.jpg?camera_label=front"],
    "category": "Hats",
    "status": "available",
    "statusLabel": "In stock",
    "options": [
      {
        "id": "color",
        "name": "Color",
        "values": [
          {
            "id": "color-0",
            "label": "Black",
            "available": true
          },
          {
            "id": "color-1",
            "label": "Slate",
            "available": true
          }
        ]
      }
    ],
    "url": "https://shop.playdjgames.com/product/camp-cap",
    "featured": false
  },
  {
    "id": "prod_enamel_mug",
    "name": "Enamel Mug",
    "tagline": "12 oz steel core, rolled rim",
    "description": "Twelve ounce enamel mug over a steel core with a rolled rim and a wrap print. Campfire safe, dishwasher tolerant, will chip honestly with age.",
    "details": [
      "12 oz capacity",
      "Enamel over steel",
      "Rolled rim, wrap print"
    ],
    "price": 26,
    "currency": "USD",
    "images": ["https://images-api.printify.com/mockup/6ab92eb4313d78541609a0a2/70768/6906/enamel-mug.jpg?camera_label=front"],
    "category": "Drinkware",
    "status": "available",
    "statusLabel": "In stock",
    "options": [],
    "url": "https://shop.playdjgames.com/product/enamel-mug",
    "featured": true
  },
  {
    "id": "prod_insulated_bottle",
    "name": "Insulated Bottle",
    "tagline": "22 oz double wall, engraved mark",
    "description": "Twenty-two ounce double-wall vacuum bottle with a powder finish and a laser-etched mark. Holds cold most of a day and hot most of a morning.",
    "details": [
      "22 oz double-wall vacuum",
      "Powder finish",
      "Laser-etched mark"
    ],
    "price": 42,
    "currency": "USD",
    "images": ["https://images-api.printify.com/mockup/6ab92eb7b89b0ed60e0390c1/125364/112599/insulated-bottle.jpg?camera_label=front"],
    "category": "Drinkware",
    "status": "available",
    "statusLabel": "In stock",
    "options": [],
    "url": "https://shop.playdjgames.com/product/insulated-bottle",
    "featured": false
  },
  {
    "id": "prod_sticker_pack",
    "name": "Sticker Pack",
    "tagline": "Four die-cut vinyl, gloss laminate",
    "description": "Four die-cut vinyl stickers on one backing sheet. Gloss laminate over the print so they survive a laptop lid, a bottle or a rained-on case.",
    "details": [
      "Four stickers per sheet",
      "Durable vinyl, gloss laminate",
      "Weather and scratch resistant"
    ],
    "price": 12,
    "currency": "USD",
    "images": [],
    "category": "Stickers",
    "status": "available",
    "statusLabel": "In stock",
    "options": [],
    "url": "https://shop.playdjgames.com/product/sticker-pack",
    "featured": true
  },
  {
    "id": "prod_die_cut_mark",
    "name": "Die-Cut Mark Sticker",
    "tagline": "Single large mark, matte vinyl",
    "description": "One large die-cut of the house mark in matte vinyl. Cut tight to the shape with no visible carrier edge once it is down.",
    "details": [
      "4 in on the long edge",
      "Matte vinyl",
      "Cut to shape, no border"
    ],
    "price": 6,
    "currency": "USD",
    "images": ["https://images-api.printify.com/mockup/6ab92ebd4969eb2e8f085ccd/72008/14861/die-cut-mark-sticker.jpg?camera_label=front"],
    "category": "Stickers",
    "status": "available",
    "statusLabel": "In stock",
    "options": [],
    "url": "https://shop.playdjgames.com/product/die-cut-mark",
    "featured": false
  },
  {
    "id": "prod_custom_tiny",
    "name": "Custom Text Sticker — Tiny",
    "tagline": "Your text, tiny die-cut vinyl",
    "description": "Your own text die-cut from durable vinyl.",
    "details": [
      "Your own text",
      "Die-cut vinyl",
      "Made to order"
    ],
    "price": 4,
    "currency": "USD",
    "images": [],
    "category": "Stickers",
    "status": "available",
    "statusLabel": "In stock",
    "options": [
      {
        "id": "size",
        "name": "Size",
        "values": [
          {
            "id": "size-0",
            "label": "2 × 2 in",
            "available": true,
            "priceDelta": 0
          }
        ]
      }
    ],
    "url": "https://shop.playdjgames.com/product/custom-text-sticker-tiny",
    "featured": false
  },
  {
    "id": "prod_custom_standard",
    "name": "Custom Text Sticker — Standard",
    "tagline": "Your text, classic die-cut vinyl",
    "description": "Your own text die-cut from durable vinyl.",
    "details": [
      "Your own text",
      "Die-cut vinyl",
      "Made to order"
    ],
    "price": 6,
    "currency": "USD",
    "images": [],
    "category": "Stickers",
    "status": "available",
    "statusLabel": "In stock",
    "options": [
      {
        "id": "size",
        "name": "Size",
        "values": [
          {
            "id": "size-0",
            "label": "3 × 3 in",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-1",
            "label": "4 × 4 in",
            "available": true,
            "priceDelta": 1
          }
        ]
      }
    ],
    "url": "https://shop.playdjgames.com/product/custom-text-sticker-standard",
    "featured": false
  },
  {
    "id": "prod_custom_large",
    "name": "Custom Text Sticker — Large",
    "tagline": "Your text, big die-cut vinyl",
    "description": "Your own text die-cut from durable vinyl.",
    "details": [
      "Your own text",
      "Die-cut vinyl",
      "Made to order"
    ],
    "price": 8,
    "currency": "USD",
    "images": [],
    "category": "Stickers",
    "status": "available",
    "statusLabel": "In stock",
    "options": [
      {
        "id": "size",
        "name": "Size",
        "values": [
          {
            "id": "size-0",
            "label": "5 × 5 in",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-1",
            "label": "6 × 6 in",
            "available": true,
            "priceDelta": 1
          }
        ]
      }
    ],
    "url": "https://shop.playdjgames.com/product/custom-text-sticker-large",
    "featured": false
  },
  {
    "id": "prod_custom_bumper",
    "name": "Custom Text Sticker — Bumper",
    "tagline": "Your text, weatherproof bumper vinyl",
    "description": "Your own text on weatherproof bumper vinyl.",
    "details": [
      "Your own text",
      "Weatherproof vinyl",
      "Made to order"
    ],
    "price": 9,
    "currency": "USD",
    "images": [],
    "category": "Stickers",
    "status": "available",
    "statusLabel": "In stock",
    "options": [
      {
        "id": "size",
        "name": "Size",
        "values": [
          {
            "id": "size-0",
            "label": "11 × 3 in",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-1",
            "label": "15 × 3.75 in",
            "available": true,
            "priceDelta": 2
          }
        ]
      }
    ],
    "url": "https://shop.playdjgames.com/product/custom-text-sticker-bumper",
    "featured": false
  },
  {
    "id": "prod_custom_window",
    "name": "Custom Car Window Decal",
    "tagline": "Your text, cut-vinyl window decal",
    "description": "Custom cut-vinyl lettering decal for your car window. Outdoor-grade and weatherproof — this is a window decal, not a vehicle wrap.",
    "details": [
      "Your own text",
      "Cut-vinyl window decal",
      "Outdoor-grade, not a wrap",
      "Made to order"
    ],
    "price": 10,
    "currency": "USD",
    "images": [],
    "category": "Stickers",
    "status": "available",
    "statusLabel": "In stock",
    "options": [
      {
        "id": "size",
        "name": "Size",
        "values": [
          {
            "id": "size-0",
            "label": "3 × 4 in",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-1",
            "label": "4 × 6 in",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-2",
            "label": "6 × 8 in",
            "available": true,
            "priceDelta": 3
          },
          {
            "id": "size-3",
            "label": "8 × 10 in",
            "available": true,
            "priceDelta": 0
          }
        ]
      }
    ],
    "url": "https://shop.playdjgames.com/product/custom-text-sticker-window",
    "featured": false
  },
  {
    "id": "prod_press_poster",
    "name": "Press Poster",
    "tagline": "Museum matte, shipped rolled",
    "description": "The house composition printed on heavy museum matte stock with deep blacks and no glare. Ships rolled in a rigid tube, unframed.",
    "details": [
      "200 gsm museum matte",
      "Archival pigment ink",
      "Ships rolled in a rigid tube"
    ],
    "price": 28,
    "currency": "USD",
    "images": ["https://images-api.printify.com/mockup/6ab92ec10d7900d72c070b74/43144/94696/press-poster.jpg?camera_label=front"],
    "category": "Posters",
    "status": "available",
    "statusLabel": "In stock",
    "options": [
      {
        "id": "size",
        "name": "Size",
        "values": [
          {
            "id": "size-0",
            "label": "18 × 24 in",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-1",
            "label": "24 × 36 in",
            "available": true,
            "priceDelta": 12
          }
        ]
      }
    ],
    "url": "https://shop.playdjgames.com/product/press-poster",
    "featured": false
  },
  {
    "id": "prod_orbit_poster",
    "name": "Orbit Poster",
    "tagline": "Orbital study, two-ink print",
    "description": "An orbital study in two inks on museum matte stock. Quiet from across a room, detailed once you are standing in front of it.",
    "details": [
      "200 gsm museum matte",
      "Two-ink composition",
      "Ships rolled in a rigid tube"
    ],
    "price": 28,
    "currency": "USD",
    "images": ["https://images-api.printify.com/mockup/6ab92ec3a4fc0c9922093abc/43144/94696/orbit-poster.jpg?camera_label=front"],
    "category": "Posters",
    "status": "available",
    "statusLabel": "In stock",
    "options": [
      {
        "id": "size",
        "name": "Size",
        "values": [
          {
            "id": "size-0",
            "label": "18 × 24 in",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-1",
            "label": "24 × 36 in",
            "available": true,
            "priceDelta": 12
          }
        ]
      }
    ],
    "url": "https://shop.playdjgames.com/product/orbit-poster",
    "featured": false
  },
  {
    "id": "prod_cassette_tee",
    "name": "Cassette Tee",
    "tagline": "Line-art cassette, heavyweight cotton",
    "description": "A line-art cassette with the house colors, printed on a heavyweight combed cotton tee. Boxy modern fit with a ribbed collar that holds its shape past the first wash.",
    "details": [
      "4.2 oz combed ring-spun cotton",
      "Boxy modern fit",
      "Water-based print, soft hand"
    ],
    "price": 34,
    "currency": "USD",
    "images": ["https://images-api.printify.com/mockup/6ab948ba7ffd41ee910caa27/18542/102044/cassette-tee.jpg?camera_label=front-2"],
    "category": "Apparel",
    "status": "available",
    "statusLabel": "In stock",
    "options": [
      {
        "id": "size",
        "name": "Size",
        "values": [
          {
            "id": "size-0",
            "label": "S",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-1",
            "label": "M",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-2",
            "label": "L",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-3",
            "label": "XL",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-4",
            "label": "XXL",
            "available": true,
            "priceDelta": 3
          }
        ]
      },
      {
        "id": "color",
        "name": "Color",
        "values": [
          {
            "id": "color-0",
            "label": "Black",
            "available": true
          },
          {
            "id": "color-1",
            "label": "Bone",
            "available": true
          },
          {
            "id": "color-2",
            "label": "Slate",
            "available": true
          }
        ]
      }
    ],
    "url": "https://shop.playdjgames.com/product/cassette-tee",
    "featured": true
  },
  {
    "id": "prod_bassline_hoodie",
    "name": "Bassline Hoodie",
    "tagline": "Waveform strip across the chest",
    "description": "A waveform strip running across the chest of a midweight brushed-back fleece pullover. Double-lined hood, split kangaroo pocket, relaxed fit.",
    "details": [
      "8 oz brushed-back fleece",
      "Double-lined hood",
      "Relaxed fit, drop shoulder"
    ],
    "price": 72,
    "currency": "USD",
    "images": ["https://images-api.printify.com/mockup/6ab948c57ffd41ee910caa31/32920/98424/bassline-hoodie.jpg?camera_label=front"],
    "category": "Apparel",
    "status": "available",
    "statusLabel": "In stock",
    "options": [
      {
        "id": "size",
        "name": "Size",
        "values": [
          {
            "id": "size-0",
            "label": "S",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-1",
            "label": "M",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-2",
            "label": "L",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-3",
            "label": "XL",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-4",
            "label": "XXL",
            "available": true,
            "priceDelta": 3
          }
        ]
      },
      {
        "id": "color",
        "name": "Color",
        "values": [
          {
            "id": "color-0",
            "label": "Black",
            "available": true
          },
          {
            "id": "color-1",
            "label": "Slate",
            "available": true
          },
          {
            "id": "color-2",
            "label": "Navy",
            "available": true
          }
        ]
      }
    ],
    "url": "https://shop.playdjgames.com/product/bassline-hoodie",
    "featured": false
  },
  {
    "id": "prod_frequency_long_sleeve",
    "name": "Frequency Long Sleeve",
    "tagline": "Equalizer bars, cotton jersey",
    "description": "An equalizer of bar shapes on long sleeve cotton jersey, with a small mark at the chest. Ribbed cuffs hold tight past the first wash.",
    "details": [
      "6 oz cotton jersey",
      "Ribbed cuffs",
      "Chest placement"
    ],
    "price": 46,
    "currency": "USD",
    "images": ["https://images-api.printify.com/mockup/6ab948cad93c97b61d03328f/33798/105264/frequency-long-sleeve.jpg?camera_label=front"],
    "category": "Apparel",
    "status": "available",
    "statusLabel": "In stock",
    "options": [
      {
        "id": "size",
        "name": "Size",
        "values": [
          {
            "id": "size-0",
            "label": "S",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-1",
            "label": "M",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-2",
            "label": "L",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-3",
            "label": "XL",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-4",
            "label": "XXL",
            "available": true,
            "priceDelta": 3
          }
        ]
      },
      {
        "id": "color",
        "name": "Color",
        "values": [
          {
            "id": "color-0",
            "label": "Black",
            "available": true
          },
          {
            "id": "color-1",
            "label": "Navy",
            "available": true
          }
        ]
      }
    ],
    "url": "https://shop.playdjgames.com/product/frequency-long-sleeve",
    "featured": false
  },
  {
    "id": "prod_turntable_poster",
    "name": "Turntable Poster",
    "tagline": "Turntable study, two-ink print",
    "description": "The turntable, rendered in two inks on museum matte stock. Reads from across the room, rewards a closer look.",
    "details": [
      "200 gsm museum matte",
      "Two-ink composition",
      "Ships rolled in a rigid tube"
    ],
    "price": 28,
    "currency": "USD",
    "images": ["https://images-api.printify.com/mockup/6ab948d1d93c97b61d03329b/43144/94696/turntable-poster.jpg?camera_label=front"],
    "category": "Posters",
    "status": "available",
    "statusLabel": "In stock",
    "options": [
      {
        "id": "size",
        "name": "Size",
        "values": [
          {
            "id": "size-0",
            "label": "18 × 24 in",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-1",
            "label": "24 × 36 in",
            "available": true,
            "priceDelta": 12
          }
        ]
      }
    ],
    "url": "https://shop.playdjgames.com/product/turntable-poster",
    "featured": false
  }
];
