/* AUTO-GENERATED by scripts/sync-presshouse.mjs — do not edit by hand. */
/* Source: https://shop.playdjgames.com (live PRESS HOUSE catalog). */
import type { StoreProduct } from "./store";

export const PRESS_HOUSE_SYNCED_AT = "2026-09-28T12:55:42.414Z";

export const PRESS_HOUSE_PRODUCTS: StoreProduct[] = [
  {
    "id": "prod_house_mark_tee",
    "name": "House Mark Tee",
    "tagline": "Heavyweight cotton, centered house mark",
    "description": "The house mark, printed small and centered on a heavyweight combed cotton tee. Boxy modern fit with a ribbed collar that holds its shape past the first wash.",
    "details": [
      "4.2 oz combed ring-spun cotton",
      "Boxy modern fit",
      "Water-based print, soft hand"
    ],
    "price": 34,
    "currency": "USD",
    "images": [
      "https://images-api.printify.com/mockup/6ab92ea0a4fc0c9922093aa5/18542/102044/house-mark-tee.jpg?camera_label=front-2"
    ],
    "category": "Apparel",
    "status": "available",
    "statusLabel": "In stock",
    "options": [
      {
        "id": "color",
        "name": "Color",
        "values": [
          {
            "id": "color-0",
            "label": "Asphalt",
            "available": true
          },
          {
            "id": "color-1",
            "label": "Black",
            "available": true
          },
          {
            "id": "color-2",
            "label": "Dark Grey",
            "available": true
          },
          {
            "id": "color-3",
            "label": "Dark Grey Heather",
            "available": true
          }
        ]
      },
      {
        "id": "size",
        "name": "Size",
        "values": [
          {
            "id": "size-0",
            "label": "S",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-1",
            "label": "M",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-2",
            "label": "L",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-3",
            "label": "XL",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-4",
            "label": "2XL",
            "available": true,
            "priceDelta": 0
          }
        ]
      }
    ],
    "featured": true,
    "pressHouseId": "prd_mukpeqbf32cbd2701c",
    "variants": [
      {
        "id": 18068,
        "color": "Asphalt",
        "size": "S"
      },
      {
        "id": 18069,
        "color": "Asphalt",
        "size": "M"
      },
      {
        "id": 18070,
        "color": "Asphalt",
        "size": "L"
      },
      {
        "id": 18071,
        "color": "Asphalt",
        "size": "XL"
      },
      {
        "id": 18072,
        "color": "Asphalt",
        "size": "2XL"
      },
      {
        "id": 18100,
        "color": "Black",
        "size": "S"
      },
      {
        "id": 18101,
        "color": "Black",
        "size": "M"
      },
      {
        "id": 18102,
        "color": "Black",
        "size": "L"
      },
      {
        "id": 18103,
        "color": "Black",
        "size": "XL"
      },
      {
        "id": 18104,
        "color": "Black",
        "size": "2XL"
      },
      {
        "id": 18140,
        "color": "Dark Grey",
        "size": "S"
      },
      {
        "id": 18141,
        "color": "Dark Grey",
        "size": "M"
      },
      {
        "id": 18142,
        "color": "Dark Grey",
        "size": "L"
      },
      {
        "id": 18143,
        "color": "Dark Grey",
        "size": "XL"
      },
      {
        "id": 18144,
        "color": "Dark Grey",
        "size": "2XL"
      },
      {
        "id": 18148,
        "color": "Dark Grey Heather",
        "size": "S"
      },
      {
        "id": 18149,
        "color": "Dark Grey Heather",
        "size": "M"
      },
      {
        "id": 18150,
        "color": "Dark Grey Heather",
        "size": "L"
      },
      {
        "id": 18151,
        "color": "Dark Grey Heather",
        "size": "XL"
      },
      {
        "id": 18152,
        "color": "Dark Grey Heather",
        "size": "2XL"
      }
    ]
  },
  {
    "id": "prod_wordmark_hoodie",
    "name": "Wordmark Hoodie",
    "tagline": "Brushed fleece with chest wordmark",
    "description": "Midweight brushed-back fleece pullover with the house wordmark across the chest. Double-lined hood, no drawcord aglets, split kangaroo pocket.",
    "details": [
      "8 oz brushed-back fleece",
      "Double-lined hood",
      "Relaxed fit, drop shoulder"
    ],
    "price": 72,
    "currency": "USD",
    "images": [
      "https://images-api.printify.com/mockup/6ab92ea563d317ccfb0c76d0/32920/98424/wordmark-hoodie.jpg?camera_label=front"
    ],
    "category": "Apparel",
    "status": "available",
    "statusLabel": "In stock",
    "options": [
      {
        "id": "color",
        "name": "Color",
        "values": [
          {
            "id": "color-0",
            "label": "Dark Heather",
            "available": true
          },
          {
            "id": "color-1",
            "label": "Navy",
            "available": true
          },
          {
            "id": "color-2",
            "label": "Black",
            "available": true
          },
          {
            "id": "color-3",
            "label": "Charcoal",
            "available": true
          }
        ]
      },
      {
        "id": "size",
        "name": "Size",
        "values": [
          {
            "id": "size-0",
            "label": "S",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-1",
            "label": "M",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-2",
            "label": "L",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-3",
            "label": "XL",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-4",
            "label": "2XL",
            "available": true,
            "priceDelta": 0
          }
        ]
      }
    ],
    "featured": true,
    "pressHouseId": "prd_mukpeqoyded617b075",
    "variants": [
      {
        "id": 32878,
        "color": "Dark Heather",
        "size": "S"
      },
      {
        "id": 32879,
        "color": "Dark Heather",
        "size": "M"
      },
      {
        "id": 32880,
        "color": "Dark Heather",
        "size": "L"
      },
      {
        "id": 32881,
        "color": "Dark Heather",
        "size": "XL"
      },
      {
        "id": 32882,
        "color": "Dark Heather",
        "size": "2XL"
      },
      {
        "id": 32894,
        "color": "Navy",
        "size": "S"
      },
      {
        "id": 32895,
        "color": "Navy",
        "size": "M"
      },
      {
        "id": 32896,
        "color": "Navy",
        "size": "L"
      },
      {
        "id": 32897,
        "color": "Navy",
        "size": "XL"
      },
      {
        "id": 32898,
        "color": "Navy",
        "size": "2XL"
      },
      {
        "id": 32918,
        "color": "Black",
        "size": "S"
      },
      {
        "id": 32919,
        "color": "Black",
        "size": "M"
      },
      {
        "id": 32920,
        "color": "Black",
        "size": "L"
      },
      {
        "id": 32921,
        "color": "Black",
        "size": "XL"
      },
      {
        "id": 32922,
        "color": "Black",
        "size": "2XL"
      },
      {
        "id": 42211,
        "color": "Charcoal",
        "size": "S"
      },
      {
        "id": 42212,
        "color": "Charcoal",
        "size": "M"
      },
      {
        "id": 42213,
        "color": "Charcoal",
        "size": "L"
      },
      {
        "id": 42214,
        "color": "Charcoal",
        "size": "XL"
      },
      {
        "id": 42215,
        "color": "Charcoal",
        "size": "2XL"
      }
    ]
  },
  {
    "id": "prod_grid_long_sleeve",
    "name": "Grid Long Sleeve",
    "tagline": "Sleeve-hit grid pattern, cotton jersey",
    "description": "Long sleeve cotton jersey with the grid motif running down the left sleeve and a small mark at the chest. Cuffs are ribbed and hold tight.",
    "details": [
      "6 oz cotton jersey",
      "Ribbed cuffs",
      "Sleeve and chest placement"
    ],
    "price": 46,
    "currency": "USD",
    "images": [
      "https://images-api.printify.com/mockup/6ab92ea9dcd154052a0154ef/33798/105264/grid-long-sleeve.jpg?camera_label=front"
    ],
    "category": "Apparel",
    "status": "available",
    "statusLabel": "In stock",
    "options": [
      {
        "id": "color",
        "name": "Color",
        "values": [
          {
            "id": "color-0",
            "label": "Black",
            "available": true
          },
          {
            "id": "color-1",
            "label": "Navy",
            "available": true
          }
        ]
      },
      {
        "id": "size",
        "name": "Size",
        "values": [
          {
            "id": "size-0",
            "label": "S",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-1",
            "label": "M",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-2",
            "label": "L",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-3",
            "label": "XL",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-4",
            "label": "2XL",
            "available": true,
            "priceDelta": 0
          }
        ]
      }
    ],
    "featured": true,
    "pressHouseId": "prd_mukper6hbf5dc93338",
    "variants": [
      {
        "id": 33796,
        "color": "Black",
        "size": "S"
      },
      {
        "id": 33797,
        "color": "Black",
        "size": "M"
      },
      {
        "id": 33798,
        "color": "Black",
        "size": "L"
      },
      {
        "id": 33799,
        "color": "Black",
        "size": "XL"
      },
      {
        "id": 33800,
        "color": "Black",
        "size": "2XL"
      },
      {
        "id": 42711,
        "color": "Navy",
        "size": "S"
      },
      {
        "id": 42712,
        "color": "Navy",
        "size": "M"
      },
      {
        "id": 42713,
        "color": "Navy",
        "size": "L"
      },
      {
        "id": 42714,
        "color": "Navy",
        "size": "XL"
      },
      {
        "id": 42715,
        "color": "Navy",
        "size": "2XL"
      }
    ]
  },
  {
    "id": "prod_house_tote",
    "name": "House Tote",
    "tagline": "Heavy canvas, flat-bottom, long strap",
    "description": "Heavy natural canvas tote with a flat bottom gusset and straps long enough for the shoulder. Printed one side with the house mark.",
    "details": [
      "12 oz cotton canvas",
      "Flat bottom gusset",
      "28 in shoulder straps"
    ],
    "price": 28,
    "currency": "USD",
    "images": [
      "https://images-api.printify.com/mockup/6ab92eac313d78541609a09c/101409/93895/house-tote.jpg?camera_label=front"
    ],
    "category": "Apparel",
    "status": "available",
    "statusLabel": "In stock",
    "options": [],
    "featured": false,
    "pressHouseId": "prd_mukperk07c709455e6",
    "variants": [
      {
        "id": 103598,
        "color": "Black",
        "size": "15\" x 16\""
      }
    ]
  },
  {
    "id": "prod_dad_hat",
    "name": "Dad Hat",
    "tagline": "Unstructured six-panel, curved brim",
    "description": "Unstructured six-panel cap in cotton twill with a low profile and a curved brim. Embroidered mark at the front panel, metal slide closure.",
    "details": [
      "Washed cotton twill",
      "Unstructured low profile",
      "Metal slide closure"
    ],
    "price": 32,
    "currency": "USD",
    "images": [
      "https://images-api.printify.com/mockup/6ab92eaf63d317ccfb0c76d4/105381/102307/dad-hat.jpg?camera_label=front"
    ],
    "category": "Hats",
    "status": "available",
    "statusLabel": "In stock",
    "options": [
      {
        "id": "color",
        "name": "Color",
        "values": [
          {
            "id": "color-0",
            "label": "Black",
            "available": true
          },
          {
            "id": "color-1",
            "label": "Navy",
            "available": true
          }
        ]
      }
    ],
    "featured": true,
    "pressHouseId": "prd_mukpervr0e0d0cca1b",
    "variants": [
      {
        "id": 105372,
        "color": "Black",
        "size": "One size"
      },
      {
        "id": 105377,
        "color": "Navy",
        "size": "One size"
      }
    ]
  },
  {
    "id": "prod_camp_cap",
    "name": "Five-Panel Camp Cap",
    "tagline": "Flat brim, nylon strap, embroidered mark",
    "description": "Five-panel camp cap with a flat brim and the monogram embroidered at the front. Nylon webbing strap with a metal clip at the back.",
    "details": [
      "Cotton twill crown",
      "Flat brim",
      "Nylon webbing strap"
    ],
    "price": 36,
    "currency": "USD",
    "images": [
      "https://images-api.printify.com/mockup/6ab92eb2a4fc0c9922093aaf/119157/109584/five-panel-camp-cap.jpg?camera_label=front"
    ],
    "category": "Hats",
    "status": "available",
    "statusLabel": "In stock",
    "options": [
      {
        "id": "color",
        "name": "Color",
        "values": [
          {
            "id": "color-0",
            "label": "Black",
            "available": true
          },
          {
            "id": "color-1",
            "label": "Grey",
            "available": true
          }
        ]
      }
    ],
    "featured": false,
    "pressHouseId": "prd_mukpes37aa2f12bbbe",
    "variants": [
      {
        "id": 119155,
        "color": "Black",
        "size": "One size"
      },
      {
        "id": 119157,
        "color": "Grey",
        "size": "One size"
      }
    ]
  },
  {
    "id": "prod_enamel_mug",
    "name": "Enamel Mug",
    "tagline": "12 oz steel core, rolled rim",
    "description": "Twelve ounce enamel mug over a steel core with a rolled rim and a wrap print. Campfire safe, dishwasher tolerant, will chip honestly with age.",
    "details": [
      "12 oz capacity",
      "Enamel over steel",
      "Rolled rim, wrap print"
    ],
    "price": 26,
    "currency": "USD",
    "images": [
      "https://images-api.printify.com/mockup/6ab92eb4313d78541609a0a2/70768/6906/enamel-mug.jpg?camera_label=front"
    ],
    "category": "Drinkware",
    "status": "available",
    "statusLabel": "In stock",
    "options": [],
    "featured": true,
    "pressHouseId": "prd_mukpesdn06c02beffc",
    "variants": [
      {
        "id": 70768,
        "color": "Default",
        "size": "12oz"
      }
    ]
  },
  {
    "id": "prod_insulated_bottle",
    "name": "Insulated Bottle",
    "tagline": "22 oz double wall, engraved mark",
    "description": "Twenty-two ounce double-wall vacuum bottle with a powder finish and a laser-etched mark. Holds cold most of a day and hot most of a morning.",
    "details": [
      "22 oz double-wall vacuum",
      "Powder finish",
      "Laser-etched mark"
    ],
    "price": 42,
    "currency": "USD",
    "images": [
      "https://images-api.printify.com/mockup/6ab92eb7b89b0ed60e0390c1/125364/112599/insulated-bottle.jpg?camera_label=front"
    ],
    "category": "Drinkware",
    "status": "available",
    "statusLabel": "In stock",
    "options": [],
    "featured": false,
    "pressHouseId": "prd_mukpespnf14c702060",
    "variants": [
      {
        "id": 125364,
        "color": "Black",
        "size": "22oz"
      }
    ]
  },
  {
    "id": "prod_sticker_pack",
    "name": "Sticker Pack",
    "tagline": "Four die-cut vinyl, gloss laminate",
    "description": "Four die-cut vinyl stickers on one backing sheet. Gloss laminate over the print so they survive a laptop lid, a bottle or a rained-on case.",
    "details": [
      "Four stickers per sheet",
      "Durable vinyl, gloss laminate",
      "Weather and scratch resistant"
    ],
    "price": 12,
    "currency": "USD",
    "images": [],
    "category": "Stickers",
    "status": "coming_soon",
    "statusLabel": "Coming soon",
    "options": [],
    "featured": true
  },
  {
    "id": "prod_die_cut_mark",
    "name": "Die-Cut Mark Sticker",
    "tagline": "Single large mark, matte vinyl",
    "description": "One large die-cut of the house mark in matte vinyl. Cut tight to the shape with no visible carrier edge once it is down.",
    "details": [
      "4 in on the long edge",
      "Matte vinyl",
      "Cut to shape, no border"
    ],
    "price": 6,
    "currency": "USD",
    "images": [
      "https://images-api.printify.com/mockup/6ab92ebd4969eb2e8f085ccd/72008/14861/die-cut-mark-sticker.jpg?camera_label=front"
    ],
    "category": "Stickers",
    "status": "available",
    "statusLabel": "In stock",
    "options": [],
    "featured": false,
    "pressHouseId": "prd_mukpet1fbe4b319ba7",
    "variants": [
      {
        "id": 72008,
        "color": "Default",
        "size": "4\" × 4\""
      }
    ]
  },
  {
    "id": "prod_custom_tiny",
    "name": "Custom Text Sticker — Tiny",
    "tagline": "Your text, tiny die-cut vinyl",
    "description": "Your own text die-cut from durable vinyl.",
    "details": [
      "Your own text",
      "Die-cut vinyl",
      "Made to order"
    ],
    "price": 4,
    "currency": "USD",
    "images": [],
    "category": "Stickers",
    "status": "coming_soon",
    "statusLabel": "Coming soon",
    "options": [
      {
        "id": "size",
        "name": "Size",
        "values": [
          {
            "id": "size-0",
            "label": "2 × 2 in",
            "available": true,
            "priceDelta": 0
          }
        ]
      }
    ],
    "featured": false
  },
  {
    "id": "prod_custom_standard",
    "name": "Custom Text Sticker — Standard",
    "tagline": "Your text, classic die-cut vinyl",
    "description": "Your own text die-cut from durable vinyl.",
    "details": [
      "Your own text",
      "Die-cut vinyl",
      "Made to order"
    ],
    "price": 6,
    "currency": "USD",
    "images": [],
    "category": "Stickers",
    "status": "coming_soon",
    "statusLabel": "Coming soon",
    "options": [
      {
        "id": "size",
        "name": "Size",
        "values": [
          {
            "id": "size-0",
            "label": "3 × 3 in",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-1",
            "label": "4 × 4 in",
            "available": true,
            "priceDelta": 1
          }
        ]
      }
    ],
    "featured": false
  },
  {
    "id": "prod_custom_large",
    "name": "Custom Text Sticker — Large",
    "tagline": "Your text, big die-cut vinyl",
    "description": "Your own text die-cut from durable vinyl.",
    "details": [
      "Your own text",
      "Die-cut vinyl",
      "Made to order"
    ],
    "price": 8,
    "currency": "USD",
    "images": [],
    "category": "Stickers",
    "status": "coming_soon",
    "statusLabel": "Coming soon",
    "options": [
      {
        "id": "size",
        "name": "Size",
        "values": [
          {
            "id": "size-0",
            "label": "5 × 5 in",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-1",
            "label": "6 × 6 in",
            "available": true,
            "priceDelta": 1
          }
        ]
      }
    ],
    "featured": false
  },
  {
    "id": "prod_custom_bumper",
    "name": "Custom Text Sticker — Bumper",
    "tagline": "Your text, weatherproof bumper vinyl",
    "description": "Your own text on weatherproof bumper vinyl.",
    "details": [
      "Your own text",
      "Weatherproof vinyl",
      "Made to order"
    ],
    "price": 9,
    "currency": "USD",
    "images": [],
    "category": "Stickers",
    "status": "coming_soon",
    "statusLabel": "Coming soon",
    "options": [
      {
        "id": "size",
        "name": "Size",
        "values": [
          {
            "id": "size-0",
            "label": "11 × 3 in",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-1",
            "label": "15 × 3.75 in",
            "available": true,
            "priceDelta": 2
          }
        ]
      }
    ],
    "featured": false
  },
  {
    "id": "prod_custom_window",
    "name": "Custom Car Window Decal",
    "tagline": "Your text, cut-vinyl window decal",
    "description": "Custom cut-vinyl lettering decal for your car window. Outdoor-grade and weatherproof — this is a window decal, not a vehicle wrap.",
    "details": [
      "Your own text",
      "Cut-vinyl window decal",
      "Outdoor-grade, not a wrap",
      "Made to order"
    ],
    "price": 10,
    "currency": "USD",
    "images": [],
    "category": "Stickers",
    "status": "coming_soon",
    "statusLabel": "Coming soon",
    "options": [
      {
        "id": "size",
        "name": "Size",
        "values": [
          {
            "id": "size-0",
            "label": "3 × 4 in",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-1",
            "label": "4 × 6 in",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-2",
            "label": "6 × 8 in",
            "available": true,
            "priceDelta": 3
          },
          {
            "id": "size-3",
            "label": "8 × 10 in",
            "available": true,
            "priceDelta": 0
          }
        ]
      }
    ],
    "featured": false
  },
  {
    "id": "prod_press_poster",
    "name": "Press Poster",
    "tagline": "Museum matte, shipped rolled",
    "description": "The house composition printed on heavy museum matte stock with deep blacks and no glare. Ships rolled in a rigid tube, unframed.",
    "details": [
      "200 gsm museum matte",
      "Archival pigment ink",
      "Ships rolled in a rigid tube"
    ],
    "price": 28,
    "currency": "USD",
    "images": [
      "https://images-api.printify.com/mockup/6ab92ec10d7900d72c070b74/43144/94696/press-poster.jpg?camera_label=front"
    ],
    "category": "Posters",
    "status": "available",
    "statusLabel": "In stock",
    "options": [],
    "featured": false,
    "pressHouseId": "prd_mukpethze882c4d24b",
    "variants": [
      {
        "id": 43144,
        "color": "Default",
        "size": "18″ x 24″"
      }
    ]
  },
  {
    "id": "prod_orbit_poster",
    "name": "Orbit Poster",
    "tagline": "Orbital study, two-ink print",
    "description": "An orbital study in two inks on museum matte stock. Quiet from across a room, detailed once you are standing in front of it.",
    "details": [
      "200 gsm museum matte",
      "Two-ink composition",
      "Ships rolled in a rigid tube"
    ],
    "price": 28,
    "currency": "USD",
    "images": [
      "https://images-api.printify.com/mockup/6ab92ec3a4fc0c9922093abc/43144/94696/orbit-poster.jpg?camera_label=front"
    ],
    "category": "Posters",
    "status": "available",
    "statusLabel": "In stock",
    "options": [],
    "featured": false,
    "pressHouseId": "prd_mukpetn5445d38101c",
    "variants": [
      {
        "id": 43144,
        "color": "Default",
        "size": "18″ x 24″"
      }
    ]
  },
  {
    "id": "prod_cassette_tee",
    "name": "Cassette Tee",
    "tagline": "Line-art cassette, heavyweight cotton",
    "description": "A line-art cassette with the house colors, printed on a heavyweight combed cotton tee. Boxy modern fit with a ribbed collar that holds its shape past the first wash.",
    "details": [
      "4.2 oz combed ring-spun cotton",
      "Boxy modern fit",
      "Water-based print, soft hand"
    ],
    "price": 34,
    "currency": "USD",
    "images": [
      "https://images-api.printify.com/mockup/6ab948ba7ffd41ee910caa27/18542/102044/cassette-tee.jpg?camera_label=front-2"
    ],
    "category": "Apparel",
    "status": "available",
    "statusLabel": "In stock",
    "options": [
      {
        "id": "color",
        "name": "Color",
        "values": [
          {
            "id": "color-0",
            "label": "Asphalt",
            "available": true
          },
          {
            "id": "color-1",
            "label": "Black",
            "available": true
          },
          {
            "id": "color-2",
            "label": "Dark Grey",
            "available": true
          },
          {
            "id": "color-3",
            "label": "Dark Grey Heather",
            "available": true
          }
        ]
      },
      {
        "id": "size",
        "name": "Size",
        "values": [
          {
            "id": "size-0",
            "label": "S",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-1",
            "label": "M",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-2",
            "label": "L",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-3",
            "label": "XL",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-4",
            "label": "2XL",
            "available": true,
            "priceDelta": 0
          }
        ]
      }
    ],
    "featured": true,
    "pressHouseId": "prd_mukpeqgw91c476a628",
    "variants": [
      {
        "id": 18068,
        "color": "Asphalt",
        "size": "S"
      },
      {
        "id": 18069,
        "color": "Asphalt",
        "size": "M"
      },
      {
        "id": 18070,
        "color": "Asphalt",
        "size": "L"
      },
      {
        "id": 18071,
        "color": "Asphalt",
        "size": "XL"
      },
      {
        "id": 18072,
        "color": "Asphalt",
        "size": "2XL"
      },
      {
        "id": 18100,
        "color": "Black",
        "size": "S"
      },
      {
        "id": 18101,
        "color": "Black",
        "size": "M"
      },
      {
        "id": 18102,
        "color": "Black",
        "size": "L"
      },
      {
        "id": 18103,
        "color": "Black",
        "size": "XL"
      },
      {
        "id": 18104,
        "color": "Black",
        "size": "2XL"
      },
      {
        "id": 18140,
        "color": "Dark Grey",
        "size": "S"
      },
      {
        "id": 18141,
        "color": "Dark Grey",
        "size": "M"
      },
      {
        "id": 18142,
        "color": "Dark Grey",
        "size": "L"
      },
      {
        "id": 18143,
        "color": "Dark Grey",
        "size": "XL"
      },
      {
        "id": 18144,
        "color": "Dark Grey",
        "size": "2XL"
      },
      {
        "id": 18148,
        "color": "Dark Grey Heather",
        "size": "S"
      },
      {
        "id": 18149,
        "color": "Dark Grey Heather",
        "size": "M"
      },
      {
        "id": 18150,
        "color": "Dark Grey Heather",
        "size": "L"
      },
      {
        "id": 18151,
        "color": "Dark Grey Heather",
        "size": "XL"
      },
      {
        "id": 18152,
        "color": "Dark Grey Heather",
        "size": "2XL"
      }
    ]
  },
  {
    "id": "prod_bassline_hoodie",
    "name": "Bassline Hoodie",
    "tagline": "Waveform strip across the chest",
    "description": "A waveform strip running across the chest of a midweight brushed-back fleece pullover. Double-lined hood, split kangaroo pocket, relaxed fit.",
    "details": [
      "8 oz brushed-back fleece",
      "Double-lined hood",
      "Relaxed fit, drop shoulder"
    ],
    "price": 72,
    "currency": "USD",
    "images": [
      "https://images-api.printify.com/mockup/6ab948c57ffd41ee910caa31/32920/98424/bassline-hoodie.jpg?camera_label=front"
    ],
    "category": "Apparel",
    "status": "available",
    "statusLabel": "In stock",
    "options": [
      {
        "id": "color",
        "name": "Color",
        "values": [
          {
            "id": "color-0",
            "label": "Dark Heather",
            "available": true
          },
          {
            "id": "color-1",
            "label": "Navy",
            "available": true
          },
          {
            "id": "color-2",
            "label": "Black",
            "available": true
          },
          {
            "id": "color-3",
            "label": "Charcoal",
            "available": true
          }
        ]
      },
      {
        "id": "size",
        "name": "Size",
        "values": [
          {
            "id": "size-0",
            "label": "S",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-1",
            "label": "M",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-2",
            "label": "L",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-3",
            "label": "XL",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-4",
            "label": "2XL",
            "available": true,
            "priceDelta": 0
          }
        ]
      }
    ],
    "featured": false,
    "pressHouseId": "prd_mukpeqv6a2e40b1178",
    "variants": [
      {
        "id": 32878,
        "color": "Dark Heather",
        "size": "S"
      },
      {
        "id": 32879,
        "color": "Dark Heather",
        "size": "M"
      },
      {
        "id": 32880,
        "color": "Dark Heather",
        "size": "L"
      },
      {
        "id": 32881,
        "color": "Dark Heather",
        "size": "XL"
      },
      {
        "id": 32882,
        "color": "Dark Heather",
        "size": "2XL"
      },
      {
        "id": 32894,
        "color": "Navy",
        "size": "S"
      },
      {
        "id": 32895,
        "color": "Navy",
        "size": "M"
      },
      {
        "id": 32896,
        "color": "Navy",
        "size": "L"
      },
      {
        "id": 32897,
        "color": "Navy",
        "size": "XL"
      },
      {
        "id": 32898,
        "color": "Navy",
        "size": "2XL"
      },
      {
        "id": 32918,
        "color": "Black",
        "size": "S"
      },
      {
        "id": 32919,
        "color": "Black",
        "size": "M"
      },
      {
        "id": 32920,
        "color": "Black",
        "size": "L"
      },
      {
        "id": 32921,
        "color": "Black",
        "size": "XL"
      },
      {
        "id": 32922,
        "color": "Black",
        "size": "2XL"
      },
      {
        "id": 42211,
        "color": "Charcoal",
        "size": "S"
      },
      {
        "id": 42212,
        "color": "Charcoal",
        "size": "M"
      },
      {
        "id": 42213,
        "color": "Charcoal",
        "size": "L"
      },
      {
        "id": 42214,
        "color": "Charcoal",
        "size": "XL"
      },
      {
        "id": 42215,
        "color": "Charcoal",
        "size": "2XL"
      }
    ]
  },
  {
    "id": "prod_frequency_long_sleeve",
    "name": "Frequency Long Sleeve",
    "tagline": "Equalizer bars, cotton jersey",
    "description": "An equalizer of bar shapes on long sleeve cotton jersey, with a small mark at the chest. Ribbed cuffs hold tight past the first wash.",
    "details": [
      "6 oz cotton jersey",
      "Ribbed cuffs",
      "Chest placement"
    ],
    "price": 46,
    "currency": "USD",
    "images": [
      "https://images-api.printify.com/mockup/6ab948cad93c97b61d03328f/33798/105264/frequency-long-sleeve.jpg?camera_label=front"
    ],
    "category": "Apparel",
    "status": "available",
    "statusLabel": "In stock",
    "options": [
      {
        "id": "color",
        "name": "Color",
        "values": [
          {
            "id": "color-0",
            "label": "Black",
            "available": true
          },
          {
            "id": "color-1",
            "label": "Navy",
            "available": true
          }
        ]
      },
      {
        "id": "size",
        "name": "Size",
        "values": [
          {
            "id": "size-0",
            "label": "S",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-1",
            "label": "M",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-2",
            "label": "L",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-3",
            "label": "XL",
            "available": true,
            "priceDelta": 0
          },
          {
            "id": "size-4",
            "label": "2XL",
            "available": true,
            "priceDelta": 0
          }
        ]
      }
    ],
    "featured": false,
    "pressHouseId": "prd_mukperca39dc9cb42e",
    "variants": [
      {
        "id": 33796,
        "color": "Black",
        "size": "S"
      },
      {
        "id": 33797,
        "color": "Black",
        "size": "M"
      },
      {
        "id": 33798,
        "color": "Black",
        "size": "L"
      },
      {
        "id": 33799,
        "color": "Black",
        "size": "XL"
      },
      {
        "id": 33800,
        "color": "Black",
        "size": "2XL"
      },
      {
        "id": 42711,
        "color": "Navy",
        "size": "S"
      },
      {
        "id": 42712,
        "color": "Navy",
        "size": "M"
      },
      {
        "id": 42713,
        "color": "Navy",
        "size": "L"
      },
      {
        "id": 42714,
        "color": "Navy",
        "size": "XL"
      },
      {
        "id": 42715,
        "color": "Navy",
        "size": "2XL"
      }
    ]
  },
  {
    "id": "prod_turntable_poster",
    "name": "Turntable Poster",
    "tagline": "Turntable study, two-ink print",
    "description": "The turntable, rendered in two inks on museum matte stock. Reads from across the room, rewards a closer look.",
    "details": [
      "200 gsm museum matte",
      "Two-ink composition",
      "Ships rolled in a rigid tube"
    ],
    "price": 28,
    "currency": "USD",
    "images": [
      "https://images-api.printify.com/mockup/6ab948d1d93c97b61d03329b/43144/94696/turntable-poster.jpg?camera_label=front"
    ],
    "category": "Posters",
    "status": "available",
    "statusLabel": "In stock",
    "options": [],
    "featured": false,
    "pressHouseId": "prd_mukpetafe0f2fc5d27",
    "variants": [
      {
        "id": 43144,
        "color": "Default",
        "size": "18″ x 24″"
      }
    ]
  }
];
